flow:
  name: upper_case_tutorial
  fail_fast: true
  work_dir: .sequor
  output_dir: output
  parallelism: 4

tasks:
  - name: uppercase
    task_type: python_fn
    depends_on: []
    cache: true
    config:
      function: tutorial.upper_case.jobs.uppercase_file
      pattern: "{pipeline_dir}/inputs/*.txt"
      item_id_template: "{input_stem}"
      output_dir: "{output_dir}/upper"

  - name: summary
    task_type: shell_cmd
    parallelism: 1
    depends_on: [uppercase]
    cache: false
    config:
      default_item:
        item_id: summary
        cmd: "python {pipeline_dir}/summarize.py --output_dir {output_dir}/upper --summary_csv {output_dir}/summary.csv"
