flow:
  name: rosetta_project_demo
  fail_fast: true
  work_dir: .sequor
  output_dir: output
  parallelism: 4

tasks:
  - name: run_rosetta_mock
    task_type: shell_cmd
    planner: csv_manifest
    depends_on: []
    cache: true
    config:
      manifest: cases.csv
      item_id_field: case_id
      cmd_template: "python {pipeline_dir}/mock_rosetta.py --pdb {pdb} --xml {xml} --out_dir {output_dir}/rosetta/{case_id} --nstruct {nstruct}"
